#index:
#    path: /
#    controller: App\Controller\DefaultController::index

insert_transaction:
  path: /transaction
  methods: put
  controller: App\Controller\TransactionController::insert

get_transactions:
  path: /transaction
  methods: get
  controller: App\Controller\TransactionController::all

get_balance:
  path: /balance
  methods: get
  controller: App\Controller\BalanceController::get
